///////////////////////////////////////////////////////////
//  ACar.cs
//  Implementation of the Class ACar
//  Generated by Enterprise Architect
//  Created on:      25-3月-2021 20:56:42
//  Original author: zeng
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class ACar {

	public string name;

	public ACar(){

	}

	public string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}
	//抽象车open方法
	public abstract void OpenCar();

}//end ACar