///////////////////////////////////////////////////////////
//  BenzCar.cs
//  Implementation of the Class BenzCar
//  Generated by Enterprise Architect
//  Created on:      25-3月-2021 20:56:40
//  Original author: zeng
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace VhFactory
{
	public class BenzCar : ACar
	{

		public BenzCar()
		{

		}

		//Benz的open方法
		public override void OpenCar()
		{
			Console.WriteLine("Benz开车");
		}

	}//end BenzCar
}