///////////////////////////////////////////////////////////
//  BenzFactory.cs
//  Implementation of the Class BenzFactory
//  Generated by Enterprise Architect
//  Created on:      25-3月-2021 20:56:45
//  Original author: zeng
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace VhFactory
{
	public class BenzFactory : ICar
	{

		public BenzFactory()
		{

		}

		//生成并返回Benz类
		public ACar GetCar()
		{
			ACar car = new BenzCar();
			return car;
		}

	}//end BenzFactory
}