///////////////////////////////////////////////////////////
//  BMWCar.cs
//  Implementation of the Class BMWCar
//  Generated by Enterprise Architect
//  Created on:      25-3月-2021 20:56:38
//  Original author: zeng
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace VhFactory
{

	public class BMWCar : ACar
	{

		public BMWCar()
		{

		}
		//BMW的open方法
		public override void OpenCar()
		{
			Console.WriteLine("BMW开车");
		}

	}//end BMWCar
}