///////////////////////////////////////////////////////////
//  Man.cs
//  Implementation of the Class Man
//  Generated by Enterprise Architect
//  Created on:      19-3月-2021 14:59:32
//  Original author: 黄芪炜
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using NvwaFactory;

namespace NvwaFactory
{
    class Man : IPerson
    {
        //显示成功生成
        public Man()
        {
            Console.WriteLine("创建男人");
        }
        
    }

}//end Man

