///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      19-3ÔÂ-2021 14:59:35
//  Original author: »ÆÜÎì¿
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace NvwaFactory
{
	public interface IPerson
	{ 

	}//end Person
}