///////////////////////////////////////////////////////////
//  Robot.cs
//  Implementation of the Class Robot
//  Generated by Enterprise Architect
//  Created on:      19-3月-2021 14:59:37
//  Original author: 黄芪炜
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace NvwaFactory
{
	class Robot : IPerson
	{
		//显示成功生成
		public Robot()
		{
			Console.WriteLine("成功创建机器人");
		}

	}
}