///////////////////////////////////////////////////////////
//  Woman.cs
//  Implementation of the Class Woman
//  Generated by Enterprise Architect
//  Created on:      19-3月-2021 14:59:38
//  Original author: 黄芪炜
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace NvwaFactory
{
	class Woman : IPerson
	{
		//显示成功生成
		public Woman()
		{
			Console.WriteLine("成功创建女人");
		}

	}//end Woman
}